In [1]:
# mnist import 

from __future__ import division, print_function, unicode_literals


import pandas as pd
import numpy as np
import os
np.random.seed(42)
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

# 한글출력
matplotlib.rc('font', family='NanumBarunGothic')
plt.rcParams['axes.unicode_minus'] = False

# 그림을 저장할 폴드
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "classification"

def save_fig(fig_id, tight_layout=True):
    path = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID, fig_id + ".png")
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format='png', dpi=300)
    
from sklearn.datasets import fetch_openml
mnist = fetch_openml("mnist_784", as_frame=False)

X, y = mnist.data, mnist.target
print(X.shape, y.shape)
y = y.astype(np.int8)

(70000, 784) (70000,)


In [31]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

data = pd.read_csv("datasets/diabetes/train.csv")

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   p_id                   614 non-null    int64  
 1   no_times_pregnant      614 non-null    int64  
 2   glucose_concentration  614 non-null    int64  
 3   blood_pressure         614 non-null    int64  
 4   skin_fold_thickness    614 non-null    int64  
 5   serum_insulin          614 non-null    int64  
 6   bmi                    614 non-null    float64
 7   diabetes pedigree      614 non-null    float64
 8   age                    614 non-null    int64  
 9   diabetes               614 non-null    int64  
dtypes: float64(2), int64(8)
memory usage: 48.1 KB


In [10]:
data.describe()

p_id  no_times_pregnant  glucose_concentration  blood_pressure  \
count  614.000000         614.000000             614.000000      614.000000   
mean   385.773616           3.853420             120.542345       68.765472   
std    223.603024           3.358126              31.252286       19.914836   
min      1.000000           0.000000               0.000000        0.000000   
25%    191.250000           1.000000              99.000000       62.000000   
50%    387.000000           3.000000             117.000000       72.000000   
75%    572.750000           6.000000             139.000000       80.000000   
max    768.000000          17.000000             197.000000      114.000000   

       skin_fold_thickness  serum_insulin         bmi  diabetes pedigree  \
count           614.000000     614.000000  614.000000         614.000000   
mean             20.244300      79.355049   31.909935           0.466342   
std              15.886083     117.709950    8.007699           0.331090   
min               0.000000       0.000000    0.000000           0.078000   
25%               0.000000       0.000000   27.300000           0.240250   
50%              23.000000      17.000000   32.000000           0.361000   
75%              32.000000     126.000000   36.600000           0.613500   
max              63.000000     846.000000   59.400000           2.420000   

              age    diabetes  
count  614.000000  614.000000  
mean    33.325733    0.348534  
std     11.929569    0.476895  
min     21.000000    0.000000  
25%     24.000000    0.000000  
50%     29.000000    0.000000  
75%     41.000000    1.000000  
max     81.000000    1.000000

In [39]:
data["diabetes pedigree"]

0      0.315
1      0.254
2      0.674
3      1.162
4      0.549
       ...  
609    0.398
610    0.471
611    0.141
612    0.262
613    0.100
Name: diabetes pedigree, Length: 614, dtype: float64

In [42]:
X = data.drop("diabetes", axis=1)
y = data['diabetes']
y

0      0
1      1
2      1
3      0
4      1
      ..
609    1
610    0
611    0
612    0
613    0
Name: diabetes, Length: 614, dtype: int64

In [54]:
y.value_counts()

0    400
1    214
Name: diabetes, dtype: int64

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [34]:
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [35]:
pred = rfc.predict(X_test)

In [36]:
pred

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1], dtype=int64)

## confusion matrix 관점

In [37]:
conf_matrix = confusion_matrix(pred, y_test)
print(conf_matrix)

[[115  31]
 [ 16  41]]


## accuracy 관점

In [38]:
from sklearn.model_selection import cross_val_score

cross_val_score(rfc, X_train, y_train, cv=3, scoring="accuracy")

array([0.75912409, 0.75912409, 0.74452555])

In [55]:
conf_matrix

array([[115,  31],
       [ 16,  41]], dtype=int64)

In [78]:
tp = conf_matrix[0,0]
fp = conf_matrix[1,0]
fn = conf_matrix[0,1]

precision  = tp / (tp + fp)
recall     = tp / (tp + fn)
f1_score   = 2*( precision * recall)/(precision + recall)

print('precision, recall and f1-score for label 0')
print('The precision for label 0 is: {0:.2f}'.format(precision))
print('The recall for label 0 is: {0:.2f}'.format(recall))
print('The f1-score for label 0 is: {0:.2f}'.format(f1_score))
print('\n')

precision, recall and f1-score for label 0
The precision for label 0 is: 0.88
The recall for label 0 is: 0.79
The f1-score for label 0 is: 0.83




In [79]:
tp = conf_matrix[1,1]
fp = conf_matrix[0,1]
fn = conf_matrix[1,0]

precision  = tp / (tp + fp)
recall     = tp / (tp + fn)
f1_score   = 2*( precision * recall)/(precision + recall)

print('precision, recall and f1-score for label 1')
print('The precision for label 1 is: {0:.2f}'.format(precision))
print('The recall for label 1 is: {0:.2f}'.format(recall))
print('The f1-score for label 1 is: {0:.2f}'.format(f1_score))

precision, recall and f1-score for label 1
The precision for label 1 is: 0.57
The recall for label 1 is: 0.72
The f1-score for label 1 is: 0.64


In [80]:
print(classification_report(pred,y_test))

              precision    recall  f1-score   support

           0       0.88      0.79      0.83       146
           1       0.57      0.72      0.64        57

    accuracy                           0.77       203
   macro avg       0.72      0.75      0.73       203
weighted avg       0.79      0.77      0.78       203



In [77]:
from sklearn.metrics import precision_score, recall_score

precision_score(y_test, pred)

0.7192982456140351

In [58]:
recall_score(y_test, pred)

0.5694444444444444

In [59]:
from sklearn.metrics import f1_score

f1_score(y_test, pred)

0.6356589147286822

# ROC

In [64]:
from sklearn.model_selection import cross_val_predict

forest_clf = RandomForestClassifier(random_state=42)
y_probas_forest = cross_val_predict(forest_clf, X_train, y_train, cv=3, method="predict_proba")

In [67]:
y_scores_forest = y_probas_forest[:, 1]

In [73]:
from sklearn.metrics import roc_curve

fpr, tpr, thresholds = roc_curve(y_train, y_scores_forest)

In [74]:
fpr

array([0.        , 0.        , 0.        , 0.00743494, 0.00743494,
       0.01115242, 0.01115242, 0.01486989, 0.01486989, 0.01858736,
       0.01858736, 0.02230483, 0.0260223 , 0.0260223 , 0.04089219,
       0.04460967, 0.04832714, 0.05204461, 0.05947955, 0.06319703,
       0.07063197, 0.07806691, 0.08178439, 0.08178439, 0.08550186,
       0.08550186, 0.08550186, 0.0929368 , 0.10037175, 0.10408922,
       0.11524164, 0.11895911, 0.12639405, 0.13011152, 0.13011152,
       0.13754647, 0.14498141, 0.14869888, 0.16356877, 0.17472119,
       0.18587361, 0.19330855, 0.20817844, 0.21189591, 0.2267658 ,
       0.23791822, 0.25650558, 0.26394052, 0.26765799, 0.27509294,
       0.28996283, 0.2936803 , 0.30111524, 0.31226766, 0.3197026 ,
       0.32713755, 0.34200743, 0.35315985, 0.3605948 , 0.36802974,
       0.37174721, 0.37918216, 0.40892193, 0.42750929, 0.43866171,
       0.44609665, 0.46840149, 0.4795539 , 0.49814126, 0.52788104,
       0.55390335, 0.56877323, 0.58364312, 0.60223048, 0.63197

In [75]:
tpr

array([0.        , 0.00704225, 0.01408451, 0.02112676, 0.03521127,
       0.06338028, 0.07042254, 0.08450704, 0.09859155, 0.11267606,
       0.12676056, 0.16197183, 0.16901408, 0.21126761, 0.21126761,
       0.23239437, 0.23239437, 0.25352113, 0.27464789, 0.30985915,
       0.32394366, 0.32394366, 0.32394366, 0.34507042, 0.35915493,
       0.41549296, 0.42957746, 0.44366197, 0.45070423, 0.46478873,
       0.47887324, 0.50704225, 0.51408451, 0.51408451, 0.52816901,
       0.55633803, 0.56338028, 0.57042254, 0.57746479, 0.58450704,
       0.59859155, 0.61267606, 0.61267606, 0.61971831, 0.61971831,
       0.63380282, 0.63380282, 0.65492958, 0.66901408, 0.68309859,
       0.69014085, 0.70422535, 0.73239437, 0.73239437, 0.73943662,
       0.75352113, 0.76056338, 0.77464789, 0.78873239, 0.79577465,
       0.80985915, 0.81690141, 0.84507042, 0.84507042, 0.86619718,
       0.87323944, 0.87323944, 0.88028169, 0.88732394, 0.88732394,
       0.8943662 , 0.9084507 , 0.9084507 , 0.91549296, 0.93661